Rest api implementation of CRUD operations with JWT checks.
DraganJankovic997/todo-backend pull request #3
Opened 2019-08-05 13:46 UTC by DraganJankovic997

2019-08-05 18:27 UTC, miljanic requested changes

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/database/migrations/2019_08_05_111613_create_todos_table.php
> +            $table->engine = 'InnoDB';
nema potrebe za ovim

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/database/migrations/2019_08_05_111613_create_todos_table.php
> +            $table->date('untill_date');
mozda da spojimo date i time u datetime?

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/database/migrations/2019_08_05_111613_create_todos_table.php
> +            $table->boolean('done');
mozda ovde da stavis default da bude false?

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function create()
znam da se samo izgenerisalo, ali brisi metode koje se ne koriste

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +        $todos = Todo::all();
nikako :scream: 
ovaj query ce ti povuci celu tabelu todos iz baze u ram
zamisli aplikaciju koju koristi milion korisnika i svaki ima 100 todo itema. to je 100 miliona todoova ucitanih u ram, aplikacija pada

mozes da uradis ovde `Todo::where('user_id', $userId)`, ali jos bolji pristup je da na user modelu i na todo modelu napravis relacije ka ovom drugom. onda bi mogao `$request->user()->todos()`

https://laravel.com/docs/5.8/eloquent-relationships

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +        $t = Todo::findOrFail($id);
ovde si ga nasao

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +            return Todo::findOrFail($id);
ovde opet saljes request na bazu koji ce istu stvar da vrati kao ono gore

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function show(Request $request, $id){
okej logika, ali sad ako obratis paznju 1 metoda u controlleru obavlja vise stvari
1. autorizaciju (da li korisnik sme da vidi taj todo)
2. dobavljanje samog todo-a
a to nije bas najbolje, pogledaj (a i pokazacu ti sutra) policy-je. mozes ih iskoristiti bas da tu logiku oko autorizacije izbacis na drugo mesto

https://laravel.com/docs/5.8/authorization#writing-policies

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +            return "Nada";
kada ubacis policy ovaj slucaj ne bi trebalo da se desi
ili ne postoji todo sa trazenim id-jem (vraca 404), ili postoji ali nije od trenutnog usera (vraca 401), ili vraca sam todo (i status 200)
generalno vracanje ovakvih poruka nije bas najbolja opcija, jer nije konzistentno kroz app

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function store(Request $request)
fino :ok_hand: 
sta se desi ako posaljes neke nevalidne podatke?
bilo bi dobro ubaciti validaciju ovde
https://laravel.com/docs/5.8/validation#form-request-validation

mislim da ovo moze krace da se napise kao `return Todo::create($request->all())` a kad ubacis validaciju onda umesto `->all()` treba `->validated()`

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function update(Request $request, $id)
ovde cemo isto sa policy-ima malo skratiti metodu

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function update(Request $request, $id)
a i sa validacijom kao i gore

2019-08-05 18:27 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +    public function destroy(Request $request, $id)
i ovde isto, trebace policy

2019-08-06 07:59 UTC, DraganJankovic997 commented on todo-backend/database/migrations/2019_08_05_111613_create_todos_table.php
> +            $table->boolean('done');
Kada se pravi novi todo, done je automatski false. ($newTodo->done = false;)

2019-08-06 12:18 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/RegisterController.php
> +        User::create($v);
bilo bi pametno i vratiti tog usera :smile:

2019-08-06 12:19 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/RegisterController.php
> +        $v = $request->validated();
izbegavaj kratka imena promenljivih, ovo moze da se zove `user` i da bude mnogo ociglednije sta je

2019-08-06 12:20 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +        Todo::create(array_merge(['user_id' => Auth::id()], $request->validated()));
i ovde bi trebalo vratiti to sto kreiras

2019-08-06 12:21 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/TodoController.php
> +        $todo = Todo::findOrFail($id);
ovde mozes kao i na drugim mestima da stavis da sam izvuce Todo po id

2019-08-06 12:23 UTC, Pseudonick47 commented on todo-backend/app/Policies/TodoPolicy.php
> +        return $user->id === $todo->user_id;
kul sto si razdvojio na razlicite metode (view, update, delete)
e sad, ponavlja se logika, mozes napraviti neku privatnu metodu u klasi ovoj (tipa isOwner) i pozivati nju na ova tri, mesta, ne znaci puno ali se reuse-uje kod

2019-08-06 13:59 UTC, Pseudonick47 commented on todo-backend/app/Http/Requests/StoreTodos.php
> +        $arr = ['LOW', 'MEDIUM', 'HIGH'];
ovo je bolje na todo model da stavis kao konstantu, koristice se jos verovatno
a dole mozes da iskoristis odatle i stavis u validacili sa implode funkcijom

2019-08-06 14:00 UTC, Pseudonick47 commented on todo-backend/app/Http/Requests/UpdateTodos.php
> +        $arr = ['LOW', 'MEDIUM', 'HIGH'];
da, evo ga opet :smile:

2019-08-06 14:01 UTC, Pseudonick47 commented on todo-backend/database/factories/TodoFactory.php
> +    $arr = ['LOW', 'MEDIUM', 'HIGH'];
hehehe nasao sam ga opet :joy:

2019-08-06 14:03 UTC, Pseudonick47 commented on todo-backend/app/Http/Controllers/RegisterController.php
> +        $ac = new AuthController;
u sustini da, ideja je super, i trenutno ne mozemo nista bolje, ali cemo zato napraviti servise
sve sto je sada u kontrolerima ce ici u servise a u kontrolerima nece biti nikakve "biznis logike"
service ce moci da se importuje u controller, jer ovako bas nema puno smisla

2019-08-06 14:47 UTC, merged